name: amenthum
favicon: null
layout_spectrum: 0.04451342509128153
typography_spectrum: 0.6543536395765841
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8102473253384233
  lightness: 0.8378505115397274
  saturation: 0.5655258337501436
  rhythmicContrast: 0.5784665087703615
purpose: []
